name: rag-agent-chunkdocs
channels:
- conda-forge
dependencies:
- pip
- poppler
- python=3.11
- pip:
  - azure-ai-documentintelligence
  - azureml-core
  - azureml-dataprep
  - azureml-dataset-runtime[pandas,fuse]
  - azureml-telemetry
  - openai
  - pandas
  - pdf2image
  - opencv-python-headless
  - semchunk
  - tenacity
  - tiktoken
  - azure-cognitiveservices-speech==1.40.0