name: rag-agent-indexchunks
channels:
- conda-forge
dependencies:
- pip
- python=3.11
- pip:
  - azure-search-documents
  - azureml-core
  - azureml-dataprep
  - azureml-dataset-runtime[pandas,fuse]
  - azureml-telemetry
  - pandas