$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
display_name: rag-agent
description: "Pipeline to ingest and index documents for RAG 2.0 agent."
settings:
  force_rerun: true

inputs:
  pipeline_job_gpt4o_deployment_name: "gpt-4o-global"
  pipeline_job_whisper_deployment_name: "whisper"
  pipeline_job_openai_embedding_model: "text-embedding-3-large"
  pipeline_job_aoai_api_version: "2024-06-01"
  pipeline_job_doc_intel_api_version: "2024-02-29-preview"
  pipeline_job_speech_region: "eastus"
  pipeline_job_max_chunk_size: 8000
  pipeline_job_azure_ai_search_index_name: "rag-agent"
  pipeline_job_vector_search_dimensions: 3072

jobs:

  chunk_docs:
    type: parallel
    inputs:
      docs_folder:
        type: uri_folder
        mode: ro_mount
        path: azureml://datastores/datalake/paths/rag-agent/docs
      gpt4o_deployment_name: ${{parent.inputs.pipeline_job_gpt4o_deployment_name}}
      whisper_deployment_name: ${{parent.inputs.pipeline_job_whisper_deployment_name}}
      openai_embedding_model: ${{parent.inputs.pipeline_job_openai_embedding_model}}
      aoai_api_version: ${{parent.inputs.pipeline_job_aoai_api_version}}
      doc_intel_api_version: ${{parent.inputs.pipeline_job_doc_intel_api_version}}
      speech_region: ${{parent.inputs.pipeline_job_speech_region}}
      max_chunk_size: ${{parent.inputs.pipeline_job_max_chunk_size}}
    outputs:
      chunks_folder:
        type: uri_folder
        mode: rw_mount
        path: azureml://datastores/datalake/paths/rag-agent/chunks
      log_file:
        type: uri_file
        mode: rw_mount
        path: azureml://datastores/datalake/paths/rag-agent/logs/chunk_docs.log
    input_data: ${{inputs.docs_folder}}
    compute: serverless
    resources:
      instance_count: 1
      instance_type: Standard_F4s_v2
    max_concurrency_per_instance: 2
    logging_level: "DEBUG"
    mini_batch_error_threshold: 2
    mini_batch_size: "1"
    retry_settings:
      max_retries: 2
      timeout: 600
    task:
      type: run_function
      code: chunk_docs
      entry_script: chunk_docs.py
      environment: azureml:rag-agent-chunkdocs@latest
      program_arguments: >- 
        --chunks_folder ${{outputs.chunks_folder}}
        --log_file ${{outputs.log_file}}
        --gpt4o_deployment_name ${{inputs.gpt4o_deployment_name}}
        --whisper_deployment_name ${{inputs.whisper_deployment_name}}
        --openai_embedding_model ${{inputs.openai_embedding_model}}
        --aoai_api_version ${{inputs.aoai_api_version}}
        --doc_intel_api_version ${{inputs.doc_intel_api_version}}
        --speech_region ${{inputs.speech_region}}
        --max_chunk_size ${{inputs.max_chunk_size}}
        --copy_logs_to_parent True
      append_row_to: ${{outputs.log_file}}

  create_index:
      type: command
      inputs:
        azure_ai_search_index_name: ${{parent.inputs.pipeline_job_azure_ai_search_index_name}}
        azure_ai_vector_search_dimensions: ${{parent.inputs.pipeline_job_vector_search_dimensions}}
      code: index_chunks
      command: >- 
        python create_index.py 
        --log_file=${{outputs.log_file}} 
        --azure_ai_search_index_name=${{inputs.azure_ai_search_index_name}} 
        --azure_ai_vector_search_dimensions=${{inputs.azure_ai_vector_search_dimensions}}
      outputs:
        log_file:
          type: uri_file
          mode: rw_mount
          path: azureml://datastores/datalake/paths/rag-agent/logs/create_index.log
      environment: azureml:rag-agent-indexchunks@latest
      compute: serverless
      resources:
        instance_count: 1
        instance_type: Standard_F4s_v2

  index_chunks:
    type: parallel
    inputs:
      create_index_log:
        type: uri_file
        mode: ro_mount
        path: ${{parent.jobs.create_index.outputs.log_file}}
      json_folder:
        type: uri_folder
        mode: ro_mount
        path: ${{parent.jobs.chunk_docs.outputs.chunks_folder}}
      azure_ai_search_index_name: ${{parent.inputs.pipeline_job_azure_ai_search_index_name}}
    outputs:
      log_file:
        type: uri_file
        mode: rw_mount
        path: azureml://datastores/datalake/paths/rag-agent/logs/index_chunks.log
    input_data: ${{inputs.json_folder}}
    compute: serverless
    resources:
      instance_count: 1
      instance_type: Standard_F4s_v2
    max_concurrency_per_instance: 3
    logging_level: "DEBUG"
    mini_batch_error_threshold: 1
    mini_batch_size: "1"
    retry_settings:
      max_retries: 3
      timeout: 120
    task:
      type: run_function
      code: index_chunks
      entry_script: index_chunks.py
      environment: azureml:rag-agent-indexchunks@latest
      program_arguments: >-
        --log_file ${{outputs.log_file}}
        --azure_ai_search_index_name ${{inputs.azure_ai_search_index_name}}
        --copy_logs_to_parent True
      append_row_to: ${{outputs.log_file}}