$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
display_name: rag-agent
settings:
  force_rerun: true

jobs:

  chunk_docs:
    type: parallel
    inputs:
      docs_folder:
        type: uri_folder
        mode: ro_mount
        path: azureml://datastores/datalake/paths/rag-agent/docs
    outputs:
      chunks_folder:
        type: uri_folder
        mode: rw_mount
        path: azureml://datastores/datalake/paths/rag-agent/chunks
      log_file:
        type: uri_file
        mode: rw_mount
        path: azureml://datastores/datalake/paths/rag-agent/logs/chunk_docs.log
    input_data: ${{inputs.docs_folder}}
    compute: serverless
    resources:
      instance_count: 1
      instance_type: Standard_F4s_v2
    max_concurrency_per_instance: 4
    logging_level: "DEBUG"
    mini_batch_error_threshold: 1
    mini_batch_size: "1"
    retry_settings:
      max_retries: 1
      timeout: 600
    task:
      type: run_function
      code: chunk_docs
      entry_script: chunk_docs.py
      environment: azureml:rag-agent-chunk_docs@latest
      program_arguments: --chunks_folder ${{outputs.chunks_folder}}
      append_row_to: ${{outputs.log_file}}

  create_index:
      type: command
      code: index_chunks
      command: python create_index.py --log_file=${{outputs.log_file}}
      outputs:
        log_file:
          type: uri_file
          mode: rw_mount
          path: azureml://datastores/datalake/paths/rag-agent/logs/create_index.log
      environment: azureml:rag-agent-json2idx@latest
      compute: serverless
      resources:
        instance_count: 1
        instance_type: Standard_F4s_v2

  index_chunks:
    type: parallel
    inputs:
      create_index_log:
        type: uri_file
        mode: ro_mount
        path: ${{parent.jobs.create_index.outputs.log_file}}
      json_folder:
        type: uri_folder
        mode: ro_mount
        path: ${{parent.jobs.chunk_docs.outputs.chunks_folder}}
    outputs:
      log_file:
        type: uri_file
        mode: rw_mount
        path: azureml://datastores/datalake/paths/rag-agent/logs/index_chunks.log
    input_data: ${{inputs.json_folder}}
    compute: serverless
    resources:
      instance_count: 1
      instance_type: Standard_F4s_v2
    max_concurrency_per_instance: 4
    logging_level: "DEBUG"
    mini_batch_error_threshold: 1
    mini_batch_size: "1"
    retry_settings:
      max_retries: 3
      timeout: 120
    task:
      type: run_function
      code: index_chunks
      entry_script: index_chunks.py
      environment: azureml:rag-agent-indexchunks@latest
      append_row_to: ${{outputs.log_file}}