name: rag-agent-doc2json
channels:
- conda-forge
dependencies:
- pip
- python=3.11
- pip:
  - azure-ai-documentintelligence
  - azureml-core
  - azureml-dataprep
  - azureml-dataset-runtime[pandas,fuse]
  - azureml-telemetry
  - pandas
  - tenacity